[package]
name = "hello_world"
version = "0.1.0"
authors = ["Sayed Maheen <sayedmaheen28@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
